name: sync modrinth listing

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-modrinth-listing:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: sync modrinth project description
        shell: pwsh
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./scripts/upload-modrinth.ps1 -Slug "multigolem" -SyncDescriptionOnly
